make_minimum_required(VERSION 3.23)
project(SimpleQueueArray C)

set(CMAKE_C_STANDARD 17)

include_directories(.)

add_executable(SimpleQueueArray
        SimpleQueue.c
        SimpleQueue.h
        SimpleQueueFunction.c)
